### PR TITLE
Reduce hard coding in SCSS and allow images to be sourced from /images instead of just the current path

### PR DESCRIPTION
**Pull request by psa**
## Summary

Reduce hard coding in SCSS
Allow images to be sourced from /images instead of just the current path

## Basic example

[Example using the new updates](view-source:https://diving.otoh.org/incident-reports/2022-08-19-freedive/)

## Motivation

Allows for easier customisation of CSS
Allows for common images (or all images if the user prefers) to be sourced from the images directory.

## Checks

- [X] Read [Create a Pull Request](https://getdoks.org/docs/contributing/how-to-contribute/#create-a-pull-request)
- [X] Supports all screen sizes (if relevant)
- [X] Supports both light and dark mode (if relevant)
- [X] Passes `npm run test`

### CODE REVIEW

**Comment by psa** [comment]
@CommanderStorm Checking in, anything you need from me to merge this?

**Comment by CommanderStorm** [comment]
No, Not that I knew..

**Comment by psa** [comment]
I don't have any windows machines to test this on and the errors don't make sense to me.

Why does it fail on `{{ $image = resources.Get (printf "%s%s" "images/" (index .Params.images 0)) }}` but not `{{ $image = resources.Get (printf "%s%s" "images/" site.Params.defaultImage) }}`? 

It's an amalgam of the line above and below. I would have figured Windows would choke on the `/` for `site.Params.defaultImage` if it was going to choke at all.

Any ideas?

**Comment by psa** [comment]
@h-enk Any ideas on this? I'm stumped as to why it doesn't run.

**Comment by h-enk** [comment]
Possibly related to: https://github.com/h-enk/doks/discussions/922#discussioncomment-3857518

**Comment by psa** [comment]
Poking the stale bot. I just haven't had time to work on this yet.

**Comment by psa** [comment]
OK, I think I've found the problem, in the form of a missing `{{end}}` which didn't show up in my testing but I just tripped over in another related change I was making.

**Comment by psa** [comment]
Or not, apparently still fails on Windows. More debugging to do.

**Comment by psa** [comment]
Or not, apparently still fails on Windows. More debugging to do.

**Comment by h-enk** [comment]
"Reduce hard coding in SCSS" is to be fixed with /related with: https://github.com/gethyas/doks-core/issues/68

"Allow images to be sourced from /images instead of just the current path" will not be supported — current (Hugo default) [Resource Locations](https://images.gethyas.com/docs/basics/resources/) should do

**Comment by h-enk** [comment]
Thanks — I'm closing your PR now

**Pull request closed without merging**
